name = "npcap"
description = "A packet capture (and sending) library for Microsoft Windows"

maintainers = ["john.serock@gmail.com"]
maintainers-logins = ["serock"]

[[external]]
kind = "hint"
hint = "Please install Npcap; it can be downloaded from https://npcap.com/"
available."case(os)".windows = true
available."case(os)"."..." = false
